time_zone: ${TIME_ZONE}
time_format: ${TIME_FORMAT}

git_executable: ${GIT_EXECUTABLE}
go_executable: ${GO_EXECUTABLE}
ffmpeg_executable: ${FFMPEG_EXECUTABLE}
debug_mode: ${DEBUG_MODE}

use_github_binaries: ${USE_GITHUB_BINARIES}
architecture: ${ARCHITECTURE}

telegram:
  bot_token: ${TELEGRAM_BOT_TOKEN}
  self_hosted_api: ${TELEGRAM_SELF_HOSTED_API}
  owner_id: ${TELEGRAM_OWNER_ID}
  sudo_users_id:
    - ${TELEGRAM_SUDO_USERS_ID}
  target_chat_id: ${TELEGRAM_TARGET_CHAT_ID}
  skip_video_stickers: ${TELEGRAM_SKIP_VIDEO_STICKERS}
  skip_setting_commands: ${TELEGRAM_SKIP_SETTING_COMMANDS}
  send_my_presence: ${TELEGRAM_SEND_MY_PRESENCE}
  send_my_read_receipts: ${TELEGRAM_SEND_MY_READ_RECEIPTS}
  silent_confirmation: ${TELEGRAM_SILENT_CONFIRMATION}
  emoji_confirmation: ${TELEGRAM_EMOJI_CONFIRMATION}

whatsapp:
  session_name: ${WHATSAPP_SESSION_NAME}
  tag_all_allowed_groups: ${WHATSAPP_TAG_ALL_ALLOWED_GROUPS}
  ignore_chats: ${WHATSAPP_IGNORE_CHATS}
  status_ignored_chats: ${WHATSAPP_STATUS_IGNORED_CHATS}
  skip_documents: ${WHATSAPP_SKIP_DOCUMENTS}
  skip_images: ${WHATSAPP_SKIP_IMAGES}
  skip_gifs: ${WHATSAPP_SKIP_GIFS}
  skip_videos: ${WHATSAPP_SKIP_VIDEOS}
  skip_voice_notes: ${WHATSAPP_SKIP_VOICE_NOTES}
  skip_audios: ${WHATSAPP_SKIP_AUDIOS}
  skip_stickers: ${WHATSAPP_SKIP_STICKERS}
  skip_status: ${WHATSAPP_SKIP_STATUS}
  skip_contacts: ${WHATSAPP_SKIP_CONTACTS}
  skip_locations: ${WHATSAPP_SKIP_LOCATIONS}
  skip_profile_picture_updates: ${WHATSAPP_SKIP_PROFILE_PICTURE_UPDATES}
  skip_group_settings_updates: ${WHATSAPP_SKIP_GROUP_SETTINGS_UPDATES}
  skip_chat_details: ${WHATSAPP_SKIP_CHAT_DETAILS}
  send_revoked_message_updates: ${WHATSAPP_SEND_REVOKED_MESSAGE_UPDATES}
  whatsmeow_debug_mode: ${WHATSAPP_WHATSMEOW_DEBUG_MODE}
  send_my_messages_from_other_devices: ${WHATSAPP_SEND_MY_MESSAGES_FROM_OTHER_DEVICES}
  sticker_metadata:
    pack_name: ${STICKER_METADATA_PACK_NAME}
    author_name: ${STICKER_METADATA_AUTHOR_NAME}

database:
  type: ${DATABASE_TYPE}
  path: ${DATABASE_PATH}
